name: Python CI/CD

on:
  push:
    branches: 
      - main
      - develop
      - pruebas
  pull_request:
    branches: 
      - main
      - develop
      - pruebas

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pyrebase pytest pytest-flask pytest-mock python-dotenv validate_email werkzeug
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Create .env file
      run: |
        echo "API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
        echo "AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env
        echo "DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> .env
        echo "PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
        echo "STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
        echo "MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
        echo "APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env
    
    - name: Run tests
      run: |
        pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to PythonAnywhere
      env:
        PYTHONANYWHERE_HOST: ${{ secrets.PYTHONANYWHERE_HOST }}
        PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        PYTHONANYWHERE_TOKEN: ${{ secrets.PYTHONANYWHERE_TOKEN }}
      run: |
        # Install PythonAnywhere CLI tool
        pip install pythonanywhere

        # Pull latest changes and restart web app
        curl -v -X POST \
          -H "Authorization: Token ${PYTHONANYWHERE_TOKEN}" \
          -H "Content-Type: application/json" \
          https://www.pythonanywhere.com/api/v0/user/${PYTHONANYWHERE_USERNAME}/webapps/${PYTHONANYWHERE_USERNAME}.pythonanywhere.com/reload/